version: '3.8'

# Development configuration - extends docker-compose.yml
services:
  claude-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DEBUG=true
      - RESTRICTED_MODE=false  # Less restrictive for development
    volumes:
      # Mount source code for hot reload
      - ./:/app
      - /app/__pycache__
    command: ["python", "-u", "main.py"]  # Unbuffered output
    stdin_open: true
    tty: true